name: reactive_file_picker
description: Wrapper around file_picker to use with reactive_forms.
version: 3.0.2
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_file_picker
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ">=16.0.0 <18.0.0"
  file_picker: ^8.0.3
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2