name: reactive_flutter_typeahead
description: Wrapper around flutter_typeahead to use with reactive_forms.
version: 3.0.0
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_flutter_typeahead
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  reactive_forms: ">=16.0.0 <18.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
