name: reactive_fluent_ui
description: Wrapper around fluent_ui to use with reactive_forms.
version: 3.0.0
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_fluent_ui
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.11.2
  reactive_forms: ">=16.0.0 <19.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
