name: reactive_dropdown_search
description: Wrapper around searchable_dropdown to use with reactive_forms
version: 6.0.0-pre3
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_dropdown_search
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ">=16.0.0 <19.0.0"
  dropdown_search: ^7.0.0-pre4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
